### PR TITLE
Add peekViewEditor colors for dark theme

### LINKED ISSUE #38: Highlight colors in peekViewEditor
I believe now default very orange color is used, so you can barely read highlight text in `alt`+`F12` window. I want to suggest more sane colors for it😄. I'm using `dark` theme

```json
"peekViewEditor.matchHighlightBackground": "#ffd33d22", // or smth else :)
"peekViewResult.matchHighlightBackground": "#ffd33d22",
```

### Current one
image

### PR DESCRIPTION
**Pull request by this-fifo**
Fix #38

### CODE REVIEW

**Comment by this-fifo** [comment]
hi @simurai , while the default colors seem to work well for the light theme they are a bit off for the dark theme as @orsenkucher pointed out

I tried using the same orange as the title for the borders but I thought the default blue looked better instead so I left that one as is

**Comment by orsenkucher** [comment]
@this-fifo now it looks a lot better bro!
Though I think we can make `background` a bit more bluish or distinct again.
And also add `"peekViewResult.matchHighlightBackground": "#ffd33d44"`,
and maybe decrease intensiveness from `#ffd33d44` to `#ffd33d33` for `peekViewEditor`

**Comment by orsenkucher** [comment]
@this-fifo @simurai, I know it can get messed up rly quickly, but we can try to approach highlights like [Pop N' Lock](https://raw.githubusercontent.com/Luxcium/pop-n-lock-theme-vscode/master/images/v3.18.0/Pop%20N'%20Lock%20Theme%20by%20Luxcium%20%E2%9C%A8%20vs%20code%20typescript%20theme%20best%20colourful%20and%20top%2010.png) did

Basically give to it some borders and matching fill color. And maybe switch from orange to bluish green color

What do you think?

**Comment by this-fifo** [comment]
I added the `peekViewResult.matchHighlightBackground` and decreased the `peekViewEditor` as you suggested, it does feel nicer! Thanks @orsenkucher 🙏

As for the blueish/distinct background, I opted for something more along the lines of other popular dark themes that rely on the borders to create visual context, here's an example of how it looks like for

[Dracula](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula) 

image

And for [Atom One Dark](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark)

image

And now github-vscode-theme

image

**Comment by orsenkucher** [comment]
Okey, sounds reasonable) I think this issue received great treatment and is basically ready to merge👍👍 @this-fifo

**Pull request merged**
