### PR TITLE
Applying theme colors to UI

### PR DESCRIPTION
**Pull request by jeffgennari**
I customized the theme to be more immersive by coloring debug tokens and symbols. Feel free to take it or leave it

### CODE REVIEW

**Comment by jeffgennari** [comment]
Just an FYI, I've updated this to work with the theme variables:

```
      "debugConsole.infoForeground": lightDark( scale.gray[6], scale.gray[3]),
      "debugConsole.warningForeground": lightDark( scale.yellow[6], scale.yellow[3]),
      "debugConsole.errorForeground": lightDark( scale.red[5], scale.red[2]),      
      "debugConsole.sourceForeground": lightDark( scale.yellow[5], scale.yellow[2]),
      "debugConsoleInputIcon.foreground": lightDark( scale.purple[6], scale.purple[3]),

      "debugTokenExpression.name": lightDark(scale.blue[6], scale.blue[2]),
      "debugTokenExpression.value": lightDark(scale.blue[8], scale.blue[1]),
      "debugTokenExpression.string": lightDark(scale.blue[8], scale.blue[1]),
      "debugTokenExpression.boolean": lightDark( scale.green[6], scale.green[2]),
      "debugTokenExpression.number": lightDark( scale.green[6], scale.green[2]),
      "debugTokenExpression.error": lightDark( scale.red[6], scale.red[2]),

      "symbolIcon.arrayForeground": lightDark( scale.orange[6], scale.orange[3]),
      "symbolIcon.booleanForeground": lightDark( scale.blue[6], scale.blue[3]),
      "symbolIcon.classForeground": lightDark( scale.orange[6], scale.orange[3]),
      "symbolIcon.colorForeground": lightDark( scale.blue[8], scale.blue[2]),
      "symbolIcon.constructorForeground": lightDark( scale.purple[8], scale.purple[2]),
      "symbolIcon.enumeratorForeground": lightDark( scale.orange[6], scale.orange[3]),
      "symbolIcon.enumeratorMemberForeground": lightDark( scale.blue[6], scale.blue[3]),
      "symbolIcon.eventForeground": lightDark( scale.gray[6], scale.gray[4]),
      "symbolIcon.fieldForeground": lightDark( scale.orange[6], scale.orange[3]),
      "symbolIcon.fileForeground": lightDark( scale.yellow[6], scale.yellow[3]),
      "symbolIcon.folderForeground": lightDark( scale.yellow[6], scale.yellow[3]),
      "symbolIcon.functionForeground": lightDark( scale.purple[6], scale.purple[3]),
      "symbolIcon.interfaceForeground": lightDark( scale.orange[6], scale.orange[3]),
      "symbolIcon.keyForeground": lightDark( scale.blue[6], scale.blue[3]),
      "symbolIcon.keywordForeground": lightDark( scale.red[6], scale.red[3]),
      "symbolIcon.methodForeground": lightDark( scale.purple[6], scale.purple[3]),
      "symbolIcon.moduleForeground": lightDark( scale.red[6], scale.red[3]),
      "symbolIcon.namespaceForeground": lightDark( scale.red[6], scale.red[3]),
      "symbolIcon.nullForeground": lightDark( scale.blue[6], scale.blue[3]),
      "symbolIcon.numberForeground": lightDark( scale.green[6], scale.green[3]),
      "symbolIcon.objectForeground": lightDark( scale.orange[6], scale.orange[3]),
      "symbolIcon.operatorForeground": lightDark( scale.blue[8], scale.blue[2]),
      "symbolIcon.packageForeground": lightDark( scale.orange[6], scale.orange[3]),
      "symbolIcon.propertyForeground": lightDark( scale.orange[6], scale.orange[3]),
      "symbolIcon.referenceForeground": lightDark( scale.blue[6], scale.blue[3]),
      "symbolIcon.snippetForeground": lightDark( scale.blue[6], scale.blue[3]),
      "symbolIcon.stringForeground": lightDark( scale.blue[8], scale.blue[2]),
      "symbolIcon.structForeground": lightDark( scale.orange[6], scale.orange[3]),
      "symbolIcon.textForeground": lightDark( scale.blue[8], scale.blue[2]),
      "symbolIcon.typeParameterForeground": lightDark( scale.blue[8], scale.blue[2]),
      "symbolIcon.unitForeground": lightDark( scale.blue[6], scale.blue[3]),
      "symbolIcon.variableForeground": lightDark( scale.orange[6], scale.orange[3]),
      "symbolIcon.constantForeground": lightDark( scale.green[6], scale.green),
```

**Comment by simurai** [comment]
> Just an FYI, I've updated this to work with the theme variables:

Ok, thanks. I solved the merge conflicts by using the updated format in https://github.com/primer/github-vscode-theme/pull/239#issuecomment-1085784844.

Mind posting a screenshot? I assume these overrides are mostly for the debug console?

debug-session

**Comment by jeffgennari** [comment]
Yes, the updates are mostly to the debug console and "Debug and Run" in the primary side bar. See the screen shot for the Github Dark Default theme.
Screen Shot 2022-04-04 at 5 21 33 AM

**Review by simurai — APPROVED** [review]
Thanks for the screenshot. 🙇 

Ok, let's get this into the next release. 👍

**Pull request merged**
