### PR TITLE
Dark tweaks

### PR DESCRIPTION
**Pull request by simurai**
This tweaks the dark version a bit. Mostly making it a bit "calmer".

Before | After
--- | ---
Screen Shot 2020-04-28 at 1 00 05 PM | Screen Shot 2020-04-29 at 3 59 34 PM

### CODE REVIEW

**Comment by simurai** [comment]
@paramaggarwal how do you like all the tweaks.. 😇 

Looking at the [diff](https://github.com/primer/github-vscode-theme/pull/8/files) it seems that inverting the color scales works well for foreground (text) colors, but not really for background colors. One reason might be that darker colors make bigger jumps, but lighter colors are closer together. Especially between `gray-000` and `gray-100`. I guess that the color scale isn't really intended to be used for light and dark mode and is more used for light backgrounds and dark foregrounds:

Screen Shot 2020-04-29 at 8 51 28 PM

Another reason is that for the dark theme, the backgrounds still have the same "depth". E.g. the background for the editor is a bit "higher/lighter" than the file explorer and console. So background and border colors for the dark theme are not inverted, just everything is a lot darker. Of course this depends a bit on the "style" how the theme should look. There are dark themes with the "inverted look" that work well. I also like this flat version with lighter borders:

Screen Shot 2020-04-27 at 11 50 56 PM

Anyways, it just felt that with the current scale we're trying to "fight the system" instead of using it. So long term, we might can consider having multiple color scales? Maybe split into something like...

```ts
export const colors = {
  light: {
    fg: ["#24292e", "#2f363d", "#444d56", "#586069", "#6a737d"],
    bg: ["#fafbfc", "#f6f8fa", "#e1e4e8", "#d1d5da", "#959da5"]
  },
  dark: {
    fg: ["#fafbfc", "#f6f8fa", "#e1e4e8", "#d1d5da", "#959da5"],
    bg: ["#24292e", "#2f363d", "#444d56", "#586069", "#6a737d" ]
  }
}
```

Then each scale can be more fine tuned for its intended use. But we don't have to solve it all at once and can experiment a bit more.

**Comment by simurai** [comment]
Here when toggling between the two versions:

dark

**Comment by paramaggarwal** [comment]
Wow, nice stuff! My eye for design isn’t as sensitive so I don’t notice the finer subtleties. But at a glance this looks so nice!

**Comment by simurai** [comment]
Picking different shades of colors is a lot more "gray". 😄 As in there is not always a clear right and wrong and is more an opinionated thing.

Anyways, I'll test this a bit locally and we can consider adding the multiple color scales.

**Comment by paramaggarwal** [comment]
Good stuff @simurai - let me know if I can help from a code perspective if you have any ideas around how we can even further improve something here. 

Looking forward to dark theme release into the VS Marketplace.

**Pull request merged**
