### PR TITLE
🐛 Fixed a syntax highlight problem

### LINKED ISSUE #88: Objects and their properties have same color
In the GitHub theme, the inbuilt objects and properties have the same color while newly created have different color.
`document.something` has the same color while `testObj.something` has a different color.
image

If we compare this with **Default Dark+** theme
image

It would be great to differentiate objects with their properties and methods.

**❤️  I LOVE THE GITHUB THEME. THANKS FOR WORKING ON IT**

### PR DESCRIPTION
**Pull request by max-programming**
I fixed an issue that I was facing with the `object.property` and `object.method()`. This PR closes #88

### CODE REVIEW

**Comment by max-programming** [comment]
## Before `object.method()`:
image

## After `object.method()`:
image

**Comment by max-programming** [comment]
Currently working on the light theme

**Comment by max-programming** [comment]
Let me know if any changes are required

**Comment by max-programming** [comment]
@simurai Have you reviewed it?

**Review by simurai — CHANGES_REQUESTED** [review]
@max-programming thanks for the PR. 🙇 

What language is this for? JavaScript? Below a quick test how your example renders on github.com:

```js
person.doSomething()
console.log()

person.name
console.memory
```

and here a screenshot in this theme:

Screen Shot 2020-12-10 at 14 04 44

Hmm.. since the goal of this theme is to stay as close to github.com as possible, I would say that `object.method()` is already correct. 👍  But `object. property` could be fixed. But only the `property` should be blue and the `object` can remain white.

Does that make sense?

**Comment by max-programming** [comment]
@simurai I actually mean that everything works fine when we do `person.property` or `person.method()`. But the issue persists when we do `document.property` or `document.method()`. I mean any built-in object has the issue. But when we create a custom object, that works fine.

**Comment by max-programming** [comment]
image
Here, `console.log()` is the problem but `person.doSomething()` is fine.
image
Here, `console.memory` is the problem but `person.name` works fine. 

Any built-in object has the issue

**Comment by max-programming** [comment]
> @max-programming thanks for the PR. 🙇
> 
> What language is this for? JavaScript? Below a quick test how your example renders on github.com:
> 
> ```js
> person.doSomething()
> console.log()
> 
> person.name
> console.memory
> ```
> 
> and here a screenshot in this theme:
> 
> Screen Shot 2020-12-10 at 14 04 44
> 
> Hmm.. since the goal of this theme is to stay as close to github.com as possible, I would say that `object.method()` is already correct. 👍 But `object. property` could be fixed. But only the `property` should be blue and the `object` can remain white.
> 
> Does that make sense?

Yeah I will try to add the blue color to the `person.name`

**Comment by max-programming** [comment]
Also, `person.name` isn't highlighted on your end because you have not initialized the `person` variable

**Comment by max-programming** [comment]
@max-programming Did not know that you updated it. I'll see if I can do something else to match it later.
Closing it

**Comment by simurai** [comment]
> @max-programming I Did not know that you updated it.

Sorry, this PR #98 only changes the colors.. as in make it lighter or darker, but doesn't change the logic. Like what should be blue and what should be red etc. So that can still be improved separately.

**Comment by cmario92** [comment]
any updates on this? 
I just noticed that I opened another issue that is related to this, but with JSON key/value pairs #129.

**Comment by simurai** [comment]
> I just noticed that I opened another issue that is related to this, but with JSON key/value pairs #129.

They might be related, but it could also be that each language needs to be defined separately. We can keep #129 open until we take a closer look.

**Comment by cmario92** [comment]
#129 was closed, any plans to add this to the next release?

**Pull request closed without merging**
