### PR TITLE
Update GitHub Dark to match github.com

### PR DESCRIPTION
**Pull request by simurai**
github.com now has an [official dark mode](https://github.blog/2020-12-08-new-from-universe-2020-dark-mode-github-sponsors-for-companies-and-more/#dark-mode). To keep this theme close to github.com, this PR does the following:

- [x] Move the existing `GitHub Dark` theme to a new repo -> [github-vscode-theme-dark](https://github.com/primer/github-vscode-theme-dark). It can still be installed via `vsix`.
- [x] Update `GitHub Dark` with the new colors. There is already a PR https://github.com/primer/github-vscode-theme/pull/95 that we could try to merge into this one.
- [x] Use functional variables

GitHub Light | GitHub Dark
--- | ---
light | dark

---

**Note**: This is the same as #98 but without the "Dimmed" version. So we could ship this in case the "Dimmed" version takes a bit longer to be finalized.

Closes https://github.com/primer/github-vscode-theme/issues/103

### CODE REVIEW

**Review by dominicegginton — APPROVED** [review]
LGTM, will be nice once merged and released to get consistent theme across vscode, codespaces and GitHub.com

**Review by nonameolsson — APPROVED** [review]

**Comment by jazg** [comment]
Will this be available for use soon?

**Comment by HDenizD** [comment]
Wake up @simurai, we have a theme to merge! 👓 😆

**Comment by simurai** [comment]
ok, this should now be published as `2.0.0` 🤖 .

**Comment by simurai** [comment]
For those that prefer the "old" dark theme, you can still install it via `.vsix` from the [github-vscode-theme-dark-classic](https://github.com/primer/github-vscode-theme-dark-classic) repo. See [Install](https://github.com/primer/github-vscode-theme-dark-classic#install) in the README. It should appear as `GitHub Dark Classic`.

Screen Shot 2021-01-20 at 13 36 03

Note that we don't plan to update it any further. But if someone wants to fork and maintain it, that's cool too.

**Comment by jaycverg** [comment]
Good thing there is the "Dark Classic" :D

**Comment by nima64** [comment]
new theme looks meh..

**Comment by musab** [comment]
The new theme is awesome! Thank you for your all your hard work @simurai! 🙏

**Comment by ahmed2m** [comment]
New theme is **very** contrast-y compared to old one with the very bright line separators between sections. Thanks for providing a version to fallback to but it's sad that it won't be maintained :/

**Comment by tjeastmond** [comment]
Have to say the new dark mode is disappointing compared to the original. I appreciate the hard work though.

**Comment by jsg2021** [comment]
> New theme is **very** contrast-y compared to old one with the very bright line separators between sections. Thanks for providing a version to fallback to but it's sad that it won't be maintained :/

Hard same. I Loved that one... I got me off Atom & it's One Dark... Looking forward to the Dim merge...

**Comment by peymanr34** [comment]
> Have to say the new dark mode is disappointing compared to the original. I appreciate the hard work though.

Agreed. I like the old one, Maybe offer it as a different theme?

**Comment by peymanr34** [comment]
Great work but I really like the old one. Maybe offer it as a different theme?

**Comment by dpunish3r** [comment]
Dark theme original was better. Please keep the 3 themes.

**Comment by devdammit** [comment]
New theme is awesome! Thanks for all your work.  🤘

But original dark theme was so pretty and concise, IMHO. 😌

**Comment by Couapy** [comment]
Oww.. Can you support the old dark theme ? I really prefer it but I don't really want to install the VSIX file.
Thank you a lot !

**Comment by simurai** [comment]
> Can you support the old dark theme ? I really prefer it but I don't really want to install the VSIX file.

@BerriJ published it to the [marketplace](https://marketplace.visualstudio.com/items?itemName=BerriJ.github-vscode-theme-dark-classic).

**Pull request merged**
