### PR TITLE
Update markdown inline code scope

### LINKED ISSUE #187: Inline code in Markdown is not colorized
I expect code blocks in Markdown to be colored/highlighted. The GitHub website gives inline code a different background and the default VSCode themes colorize inline code.

Using [this repo's README](https://github.com/primer/github-vscode-theme/blob/66f9446a8311ddd1adb8c12ce857d839c4427d95/README.md) as an example, note how inline code differs from the "new" in color/highlighting outside of the GitHub VSCode themes.

|   |   |
|---|---|
| "GitHub Light Default Theme" in VSCode  | image|
| "GitHub Dark Default Theme" in VSCode   |  image|
| "Light +"  Theme in VSCode |  image|
|  "Dark +" Theme in VSCode | image |
| GitHub Website Light Theme  | image |
| GitHub Website Dark Theme  | image  |

This also happens with the "Dimmed" themes.

### PR DESCRIPTION
**Pull request by serpilacar**
Fixes #187 

Previously:
Screenshot 2022-01-06 at 13 06 40
Screenshot 2022-01-06 at 14 06 26
Screenshot 2022-01-06 at 14 06 36

With this PR:
Screenshot 2022-01-06 at 13 18 12
Screenshot 2022-01-06 at 13 39 59
Screenshot 2022-01-06 at 22 17 11

### CODE REVIEW

**Review by dominicegginton — APPROVED** [review]

**Comment by mangobat** [comment]
Tested it and it solves the issue for me, thanks @serpilacar!

**Review by simurai — COMMENTED** [review]
Wouldn't this change just affect the `foreground` and make it blue when editing a markdown file? But how I understood https://github.com/primer/github-vscode-theme/issues/187 is that there should be a background color for the "markdown preview" like when a .md file gets rendered on github.com?

Screen Shot 2021-08-09 at 17 52 27

/cc @mangobat

**Comment by serpilacar** [comment]
> Wouldn't this change just affect the `foreground` and make it blue when editing a markdown file? But how I understood #187 is that there should be a background color for the "markdown preview" like when a .md file gets rendered on github.com?
> 
> Screen Shot 2021-08-09 at 17 52 27
> 
> /cc @mangobat

The problem -as I understood from related issue- is inline code is lack of highlighting which makes it look like just a random text. The funny thing is there was just a typo on scope's keyword :)

**Comment by ScriptAutomate** [comment]
@serpilacar @simurai This has been one of things preventing me for adopting these themes, since I work with large amounts of Markdown files.

- Is there a screenshot of the difference this makes in the editor?
- And are there any other steps required for this PR to be considered as ready to be merged?

Other themes ensure that `inline code like this` will look different within the editor, and seeing the text being the same (as shown in #187) makes it difficult for the eyes to see where inline code is being used when editing.

**Comment by serpilacar** [comment]
I've updated the branch so it's sync with latest version of primer/main. One question on my mind is: does really `dimmed` key on theme config work for others? shouldn't it be referenced as `dark_dimmed` instead? It's named as that in `src/colors.js` and `src/index.js` as well 🤔

**Comment by simurai** [comment]
> does really `dimmed` key on theme config work for others? shouldn't it be referenced as `dark_dimmed` instead?

Yes, I think that would make sense. 👍 

Sorry, we're a bit slow in merging PRs. And there is also https://github.com/primer/github-vscode-theme/pull/244 that makes some bigger changes and might conflict again. 😇

**Review by simurai — COMMENTED** [review]
@serpilacar Sorry, this PR became un-mergable. It seems the only markdown related change was this https://github.com/primer/github-vscode-theme/pull/193/commits/16c78ed1bde861746ad77382c041a290f6340110#diff-09ce39aad75bba2010ea6e7fb785187ec76b341be11d5f7f2cc6b83839a1b728L481-R481.

So I [resolved the merge conflicts](https://github.com/primer/github-vscode-theme/pull/193/commits/b33e4a94621b479db1037da9735864c35984742d) caused by renaming `dimmed` and only pushed the [scope change](https://github.com/primer/github-vscode-theme/pull/193/commits/378b08a52a98b70da7b9f0b190ded01f7f3108ef). Is that ok?

**Comment by serpilacar** [comment]
> @serpilacar Sorry, this PR became un-mergable. It seems the only markdown related change was this [16c78ed#diff-09ce39aad75bba2010ea6e7fb785187ec76b341be11d5f7f2cc6b83839a1b728L481-R481](https://github.com/primer/github-vscode-theme/commit/16c78ed1bde861746ad77382c041a290f6340110#diff-09ce39aad75bba2010ea6e7fb785187ec76b341be11d5f7f2cc6b83839a1b728L481-R481).
> 
> So I [resolved the merge conflicts](https://github.com/primer/github-vscode-theme/pull/193/commits/b33e4a94621b479db1037da9735864c35984742d) caused by renaming `dimmed` and only pushed the [scope change](https://github.com/primer/github-vscode-theme/pull/193/commits/378b08a52a98b70da7b9f0b190ded01f7f3108ef). Is that ok?

Yes 👍

**Review by simurai — APPROVED** [review]
Ok, let's 🚢  this.

**Pull request merged**
