### PR TITLE
Dark High Contrast theme + V2 colors

### PR DESCRIPTION
**Pull request by simurai**
- Adds a new `GitHub Dark High Contrast` theme. That matches the [settings on github.com](https://github.com/settings/appearance).

GitHub Dark High Contrast

- Updates `@primer/primitives` and uses the [V2 colors](https://github.com/primer/primitives/tree/main/data/colors_v2). Now that it's being enabled on github.com. There are probably quite a few regressions because in V2 a lot of variables are not available anymore and needed to be mapped to [new variables](https://github.com/primer/primitives/blob/97d4c3fd7843238799a66b45387ca92ce9f1f869/data/colors_v2/vars/deprecated.ts).

GitHub VS Code theme

### CODE REVIEW

**Comment by simurai** [comment]
In case anyone wants to give this PR a try:

1. Download the [github-vscode-theme-5.0.0-preview.vsix](https://github.com/primer/github-vscode-theme/blob/v2/github-vscode-theme-5.0.0-preview.vsix) file.
2. Then in VS Code go to the extensions panel, click on the `...` dropdown and choose "Install from VSIX..."'
    Screen Shot 2021-09-06 at 13 54 16
3. Reload VS Code
4. And now the "GitHub Dark High Contrast" theme should be available.
    Screen Shot 2021-09-06 at 13 59 31

**Comment by mazhengcn** [comment]
I found a bug that the updated file in the explore shows dark instead of green for the new 5.0.0 preview version. Stable version 4.2.1 has no issues.

5.0.0:
image

4.2.1:
image

**Comment by simurai** [comment]
> @mazhengcn I found a bug that the updated file in the explore shows dark instead of green for the new 5.0.0 preview version. Stable version 4.2.1 has no issues.

Thanks for testing. 🙇  Should be fixed by https://github.com/primer/github-vscode-theme/pull/203/commits/7312381b43caa2316760647c145ddb5844669a44.

**Comment by binhle113** [comment]
> - Adds a new `GitHub Dark High Contrast` theme. That matches the [settings on github.com](https://github.com/settings/appearance).
> 
> Dark High Contrast
> 
> - Updates `@primer/primitives` and uses the [V2 colors](https://github.com/primer/primitives/tree/main/data/colors_v2). Now that it's being enabled on github.com. There are probably quite a few regressions because in V2 a lot of variables are not available anymore and needed to be mapped to [new variables](https://github.com/primer/primitives/blob/97d4c3fd7843238799a66b45387ca92ce9f1f869/data/colors_v2/vars/deprecated.ts).
> 
> GitHub VS Code theme

**Pull request merged**
