### PR TITLE
sync dark colors with new official GitHub dark theme

### LINKED ISSUE #96: Colours don’t match with GitHub dark mode
GitHub [now has an official dark mode](https://techcrunch.com/2020/12/08/github-gets-a-dark-mode/). The colour palette it uses for code doesn’t match that of the VS Code theme:

Screen Shot 2020-12-09 at 11 19 53 pm

Screen Shot 2020-12-09 at 11 20 10 pm

### PR DESCRIPTION
**Pull request by borisimple**
Github has announced new dark theme. Let's sync editor background colors to be the same.

Closes #96

### CODE REVIEW

**Comment by sambeckingham** [comment]
Wondered if someone else had this thought - I actually prefer the current scheme to official dark scheme though.  Could we possibly have both?  Maybe call the current one Gray or Original Dark or something?

**Comment by borisimple** [comment]
Sure, that could do the trick!

**Comment by bdmac** [comment]
I'm conceptually fine with having a third version if that's something we want as long as `GitHub Dark` matches the official dark theme so things flow through properly from GH through Codespaces! :-)

**Comment by simurai** [comment]
I'm also on board keeping `GitHub Light` and `GitHub Dark` as close to github.com as possible. 👍   But keeping the current dark version should be fine too. At least for now. Here the before/after of this PR:

Before | After
--- | ---
Screen Shot 2020-12-10 at 15 20 08 | Screen Shot 2020-12-10 at 15 16 28
 
I can look into moving the existing dark version to a new name.. maybe `GitHub SpaceGray`? 🤔

**Comment by simurai** [comment]
Ok, with https://github.com/primer/github-vscode-theme/pull/98/commits/2b069bfddbd0c64ab40c082a5a37fcb961d1a07a this should now be part of https://github.com/primer/github-vscode-theme/pull/98. It uses the new colors from https://github.com/primer/primitives/pull/18. There is still some more tweaking to do to invert the rest of the color scale.

**Comment by simurai** [comment]
> Wondered if someone else had this thought - I actually prefer the current scheme to official dark scheme though. Could we possibly have both? Maybe call the current one Gray or Original Dark or something?

👋  @sambeckingham Just wanted to give an update in regards of keeping the old dark theme. We decided to move it to a new repo [primer/github-vscode-theme-dark](https://github.com/primer/github-vscode-theme-dark). It isn't published and also won't be maintained. But if someone wants to fork and put it up on the Marketplace, feel free. I changed the name to `GitHub Dark Classic` to not clash with `GitHub Dark`.

For this repo we would like to keep it the same as you will see on https://github.com/settings/appearance. And in PR https://github.com/primer/github-vscode-theme/pull/98 we already explore a second dark theme called `GitHub Dimmed`. Hope that is an acceptable compromise.

**Pull request closed without merging**
