### PR TITLE
Revert dark changes

### PR DESCRIPTION
**Pull request by simurai**
After the `2.0.0` release we got a lot of feedback asking to keep the old dark theme. This reverts all the changes to the Dark theme (also some to Light) and should be the same as `1.1.5`.

### What about the dark theme from github.com?

We're still evaluating the best path forward. An option could be to release [all the themes from github.com](https://github.com/settings/appearance) under a different name. For example `GitHub.com Dark`.

### CODE REVIEW

**Comment by fi3ework** [comment]
Maybe can provide multiple dark themes. I prefer the new dark mode and I install a 2.0.1 version to downgrade from 3.0.

**Comment by Harry-Harrison** [comment]
I also liked the dark-dark version over the grey-dark one. It's the Github theme, it should "match" GitHub, no?

**Comment by ggirotto** [comment]
Guys, you probably received only the feedback from who didn't like the new dark theme, but haven't received from those that loved it, like me.

**Comment by julio-nf** [comment]
At first I didn't like the new dark theme, but after several hours I loved it. The colors of the text are much better and easy to understand. Launching in the same extension with another name like GitHub Dark+ or something like that would be great.

**Comment by alexmigf** [comment]
I'm with you @julio-nf, initially was hard but now I want it back :disappointed:

**Comment by dominicegginton** [comment]
I think we should release the offical GitHub.com dark and light theme along with a dimmed version (the old dark theme) all within this one extention. Personaly I like the new dark theme but can see why we need the option for the old dark theme too as it can be easier on the eyes.

**Comment by dok42** [comment]
Imho the 2.0.1 dark version has a stronger identity than this revert. I've tried maybe every theme and color scheme out there and now I only have the default Dark+ and the 2.0.1 Github Theme. 
I would very slightly dim the 2.0.1 version, to avoid too much contrast, or at very least meet in between the Old Dark and the "what would have been" the new dark. 
Also this should be the same in github.com, for better UX.

**Comment by michael0liver** [comment]
Thanks for this!

**Comment by joshmanders** [comment]
I don't see why caving to complainers, the whole point of this theme is to be GitHub themed, the new dark theme is GitHub's OFFICIAL dark theme, not an alternative created based off the official white theme to satisfy people. IMO the old dark theme should be split out or made as an alternative in this one.

Those people who don't like the new official dark theme can fork v1.1.5 and maintain it themselves.

**Comment by 0xAndrewBlack** [comment]
I agree with the ones who support the new change.
It should match the OFFICIAL GitHub site theme so I don't get why was it necessary to revert it.
I just noticed a few minutes ago on my work PC that the theme is synced but the old gray is showing not the new like on my main PC after checking out the repo and seeing this nonsense.
But to fit every need there should be a fork or multiple options to choose from imo.

**Comment by Harry-Harrison** [comment]
> I think we should release the offical GitHub.com dark and light theme along with a dimmed version (the old dark theme) all within this one extention. Personaly I like the new dark theme but can see why we need the option for the old dark theme too as it can be easier on the eyes.

This makes the most sense I think. Would mean that there's one GitHub theme package with a higher install count and shared updates instead of maintaining multiple repos with fixes and things.

**Comment by HazemAM** [comment]
I also think the grey one should be listed in the same extension under a different name, e.g. "GitHub Dark (legacy)" or something similar. I like the newer one more, but I totally understand why the decision was reverted.

For now I'm going to use version 2.0.1 of the extension through VS Code's "Install another version..." option.

**Comment by leepowelldev** [comment]
Like others initially I thought the new darker theme was too much, but after a few hours I really liked it. Now the previous dark theme looks a bit washed out. I'd also suggest releasing the old/current dark version under a new theme name is the best way forward and keep this in sync with the official Github colour palette.

**Comment by fxn** [comment]
Isn't the point of this theme to match GitHub? What _some_ users think is irrelevant, the only thing that is relevant is that the theme matches GitHub today. If you do not like the theme in GitHub, just do not pick this extension.

**Comment by Gameghostify** [comment]
Reverting back to 2.0.1 as well, the update was awesome

**Comment by mcboat** [comment]
The new dark theme was great; it was a change from the previous one, but it massively aided with contrast and accessibility, and still kept the same great color scheme.

I think that reverting it was a little bit silly; change is inevitable, and the changes you guys made were productive, so why go back on them?

**Comment by simurai** [comment]
> I think we should release the offical GitHub.com dark and light theme along with a dimmed version (the old dark theme) all within this one extention.

This is technically possible, yes. But the new themes have been completely rewritten to use a new color "system" from [primer/primitives](https://github.com/primer/primitives) that is not compatible with the current one. So having separate repos/extensions is less confusing and easier to maintain.

> Isn't the point of this theme to match GitHub?

Yes, that has been the goal of this theme from the beginning. But it seems there are a lot of people that use `GitHub Dark` not because they want it to match github.com, but rather because they specifically like the colors and characteristics of that theme. See [1](https://github.com/primer/github-vscode-theme/pull/102), [2](https://github.com/primer/github-vscode-theme/issues/108), [3](https://github.com/primer/github-vscode-theme/issues/110), [4](https://github.com/primer/github-vscode-theme/issues/112), [5](https://github.com/primer/github-vscode-theme/issues/119), [6](https://github.com/primer/github-vscode-theme/issues/120) and [marketplace reviews](https://user-images.githubusercontent.com/378023/105502508-d9323580-5d08-11eb-943b-9ac71027fdf4.png). I guess the "mistake" was to release a dark GitHub theme even though github.com didn't have a dark mode yet. And assume we can just change it later and most people are ok with it.

Here the first (reverted) attempt we tried:

- Rename `GitHub Dark` to `GitHub Dark Classic`. Move it to a different repo. Let users install it via `.vsix`. Soon later it also got forked and published on the [marketplace](https://marketplace.visualstudio.com/items?itemName=BerriJ.github-vscode-theme-dark-classic).
- In this repo, change the colors of the `GitHub Dark` to match github.com

This turned out to be too disruptive for a lot of users.. so here another attempt we're considering:

- Leave `GitHub Dark` as is. Also the existing `GitHub Light`.
- Publish the new dark theme (that matches github.com) under a different extension with a different name. For example `GitHub.com Dark`. Also the `GitHub.com Light` and other new themes that are planned.

Since we only get one shot at naming these themes (without upsetting anyone), we have to be pretty sure it's the right name for the long term. Here a few options that came to mind:

1. `GitHub.com Dark`
2. `GitHub Dark+` as suggested above https://github.com/primer/github-vscode-theme/pull/123#issuecomment-766069087
3. `GitHub Dark 2` this would kinda be adding a version number to the theme name. But a bit confusing since this extension is already using `3.0.0`.
4. `GitHub Codespaces Dark` since initially this theme was created for the [Codespaces](https://github.com/features/codespaces) feature
5. `GitHub Dotcom Dark`

Please comment if anyone has more ideas. 🙇  Personally I like `GitHub.com Dark` the best because it should make it clear what the theme is trying to do.

**Comment by johnnyhuy** [comment]
I like the idea of GitHub.com Dark.

Perhaps we can leave a disclaimer on this repo to acknowledge that the scheme here doesn't adhere to the *true* theme of GitHub.com and that if they're curious they can get a link to the GitHub.com Dark extension page.

**Comment by Harry-Harrison** [comment]
Am I right I'm thinking the current setup makes it difficult to have more than two colourways in one extension? Because if not, having a new "GitHub.com" extension that supports the current and all future themes to GitHub.com I feel would be easier to maintain and update?

**Comment by tbolt** [comment]
Bring back the new Dark!

**Comment by joshmanders** [comment]
@simurai the problem with the suggestion is that this theme is already considered the official theme. If people see two different GitHub themes, they're gonna look at install count and go "Well I'm gonna go with the one that's installed the most, because that one is most likely the correct one" then you're gonna have issues with people asking why the "official GitHub dark theme" doesn't match github.com

I think it's silly to create a whole new official theme because of the old dark version. This theme is the official GitHub theme, if I switch to dark, I should get the dark theme that matches GitHub's dark theme, not some old theme.

Put in the changelog that the old dark theme is deprecated, here's another repo they can get the `.vsix` file from if they want to go with that, or they can use VSCode's "install version ..." to go back to the last known version they like.

Pandering to people who complain because the official dark theme has been updated to match the official dark theme on the website and forcing everyone to go to a new theme that is confusing in naming is a strange concept.

**Comment by julio-nf** [comment]
I agree with @joshmanders, If the new dark is the official theme and the one that will be evolved it makes sense to be the default theme of the extension and those who dont like it are instructed to use the previous version with the built-in vscode functionality or with another extension.

**Comment by Harry-Harrison** [comment]
Yeah, i agree. I'd like to add, the dark-dark theme is rad and I super appreciate all of the effort put into the site theme and the vscode theme too.

**Comment by Gameghostify** [comment]
Most of the complaints seemed to be about the background/text contrast anyways? 

I honestly think that adding a dimmed version and keeping the 2.0-dark version will make everyone happy. It would be easier to maintain.

If someone really wants to go back to the old token colors (not just the dimmed version) they can still go back to 1.15/3.0 or install the .vsix from the repo that was made for exactly that use case

**Comment by misolori** [comment]
My vote would be to have all of the themes under one extension with different theme names (Dark, Dark+, etc.). The "multiple extensions" makes it more confusing to me (as a user) and it's very common for other themes to have multiple variants under the same extension. Maybe the tooling should be updated to reflect this, if that is the ultimate goal?

**Comment by simurai** [comment]
> Am I right I'm thinking the current setup makes it difficult to have more than two colourways in one extension?
> My vote would be to have all of the themes under one extension with different theme names (Dark, Dark+, etc.).

The new themes have been completely rewritten to use a new color "system" from [primer/primitives](https://github.com/primer/primitives) that is not compatible with the current one. So having separate repos/extensions would keep things simpler. But I think it should still be possible to use two versions of the same npm package. Or because the old colors will not change anymore, we might could just hard code so that only the newer themes would use the [primer/primitives](https://github.com/primer/primitives) package.

Maybe something to try out.

**Comment by tjeastmond** [comment]
Despite opinions, one way or another, I appreciate the effort put into making these themes.

**Comment by joshmanders** [comment]
> Despite opinions, one way or another, I appreciate the effort put into making these themes.

Yes absolutely, @simurai thank you. I've been a long time user of Dracula Theme everywhere, but I *REALLY* like the new GitHub dark theme and want to swap Dracula out in everything for it.

**Comment by TheOtterlord** [comment]
I am really liking the new theme and love the idea of using `GitHub.com Dark` as the name. 

Since there are a few different names, let's do some unofficial polling.

- 👍 `Github.com Dark`
- 👎 `Github Dark+`
- 😄 `Github Dark 2`
- 🎉 `Github Codespaces Dark`
- 😕 `Github Dotcom Dark`

**Comment by johnnyhuy** [comment]
> So having separate repos/extensions would keep things simpler. But I think it should still be possible to use two versions of the same npm package.

@simurai best choice from a user's perspective would probably having additional themes under the same extension. Though this seems like it would compromise maintainability, hopefully we can try hard-code it for now and keep it legacy in the repo going forward.

> we might could just hard code them so that only the newer themes would use the primer/primitives package.

I'm okay with either options, but we can try the one you've proposed 🙂

**Comment by MichaelKheel** [comment]
Thanks a lot for listening to the community and bringing back the old theme. 🥰

**Comment by jmotes** [comment]
Maybe this has already been said - I really liked the appearance of the new theme, but it just had too much contrast between code and background - even more than the code views on github.com. I have an astigmatism in one of my eyes that fluctuates  so can't be 100% corrected with glasses and it just made it very evident that I was seeing double text while I didn't have that issue with the old theme.

**Comment by dok42** [comment]
Could it be possible to have more themes, (in one repo/extension/bundle) like this? 
- "Github Light"
- "GitHub Dark" _this is the official dark version and matches Github.com_
- "GitHub Dimmed _this could have the same colors as GitHub Dark but a dimmed background_
- GitHub Owl _it is an example, again, just a differend background color_
- etc etc..

Could it be possible with the new color "system" to generate some few more themes variant, just with a different background color, so to have some contrast alternative?

ps: sorry for my English :)

**Comment by simurai** [comment]
> Would it be possible to make the contrast configurable?

There's not some sort of setting to only control the contrast. So it would have to be a different theme, like adding a `GitHub.com HighContrast` theme. We plan to add more themes to github.com, so this VS Code theme could include them too.

> Could it be possible with the new color "system" to generate some few more themes variant, just with a different background color, so to have some contrast alternative?

To only change the editor background color, you could already try that in your VS Code `settings.json` file. See the [Workbench colors docs](https://code.visualstudio.com/api/extension-guides/color-theme#workbench-colors).

```json
"workbench.colorCustomizations": {
  "editor.background": "#161B22"
}
```

bg

Small difference might be fine. But if the custom color is too far away from the original, it starts to clash with the rest of the theme.

**Comment by stellirin** [comment]
Since it's been stated that the two theme systems are incompatible, why not 'simply' move the unofficial dark theme to a dedicated `GitHub Theme (Legacy)` and leave it to the community to maintain it.

People that care enough will do the work to find the legacy variant and use it, everyone else will be updated to a theme that is true to the official colours, which is exactly what most people will expect going forwards.

Eventually, people will start opening bugs to show that the theme does not match the official colours etc (if they didn't already).

**Comment by Gameghostify** [comment]
@stellirin That was already done, the issue is that too many people found the change disruptive

**Comment by TheOtterlord** [comment]
@Gameghostify I think that was because you had to install it via the file, not in the marketplace 🤔 (I may be wrong here)

**Comment by Gameghostify** [comment]
> @Gameghostify I think that was because you had to install it via the file, not in the marketplace 🤔 (I may be wrong here)

Some people published it on the marketplace (there just was no _official_ extension)

**Comment by simurai** [comment]
Ok, https://github.com/primer/github-vscode-theme/pull/132 adds the `GitHub.com Light` + `GitHub.com Dark` themes (a 2nd time with a new name) and still keeps the current themes unchanged:

- `GitHub.com Light` ✨  new ✨ 
- `GitHub.com Dark` ✨  new ✨ 
- `GitHub Light` stays as is
- `GitHub Dark` stays as is

**Comment by michael0liver** [comment]
@simurai Thank you!

**Pull request merged**
